export const seasons = [
  {
    year: "2023",
    theme: "Going green through sports",
    images: [
      "/images/23/rausha-1.jpg",
      "/images/23/rausha-2.jpg",
      "/images/23/rausha-3.jpg",
      "/images/23/rausha-4.jpg",
      "/images/23/rausha-5.jpg",
      "/images/23/rausha-6.jpg",
      "/images/23/rausha-5.jpg",
      "/images/23/rausha-6.jpg",
    ],
  },
  {
    year: "2022",
    theme: "Going green through sports",
    images: [
      "/images/23/rausha-2.jpg",
      "/images/23/rausha-1.jpg",
      "/images/23/rausha-3.jpg",
      "/images/23/rausha-4.jpg",
      "/images/23/rausha-5.jpg",
      "/images/23/rausha-6.jpg",
      "/images/23/rausha-5.jpg",
      "/images/23/rausha-6.jpg",
    ],
  },
  {
    year: "2021",
    theme: "Going green through sports",
    images: [
      "/images/23/rausha-3.jpg",
      "/images/23/rausha-1.jpg",
      "/images/23/rausha-2.jpg",
      "/images/23/rausha-4.jpg",
      "/images/23/rausha-5.jpg",
      "/images/23/rausha-6.jpg",
      "/images/23/rausha-5.jpg",
      "/images/23/rausha-6.jpg",
    ],
  },
  {
    year: "2018",
    theme: "Going green through sports",
    images: [
      "/images/23/rausha-4.jpg",
      "/images/23/rausha-1.jpg",
      "/images/23/rausha-2.jpg",
      "/images/23/rausha-3.jpg",
      "/images/23/rausha-5.jpg",
      "/images/23/rausha-6.jpg",
      "/images/23/rausha-5.jpg",
      "/images/23/rausha-6.jpg",
    ],
  },
];
